version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/release
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: aws/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/start_server.sh
      timeout: 300
      runas: root
  #ApplicationStop:
  #  - location: scripts/stop_server.sh
  #    timeout: 300
  #    runas: root
