name: Deploy on EC2

on:
  workflow_dispatch: {}

env:
  applicationfolder: /
  AWS_REGION: us-east-1
  S3BUCKET: webserver-setup-us-east-1-codepipeline-183224015637

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
    steps:
    - name: Checkout codigo 
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Clean install
      run: npm ci

    - name: Verificar npm
      run: npm test